# Jekyll configuration

name: Mouse的博客
description: 记录学习生活工作的点滴

# url is currently only used only for the RSS feed in feed.xml
url: https://gongchangyou.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl:

# This can be '' to hide the Github nav button
github: 'gongchangyou/gongchangyou.github.io'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: true

permalink: /:year/:month/:title
paginate: 3

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: images/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: images/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.     
apple_icon: images/favicon.ico ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.
author_img: images/favicon.ico ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.
banner_img: #img/banner.jpg ## size:1920px*200px+. Banner Picture